<?php

/**
 * Implements hook_menu().
 */
function feeds_dashboard_menu() {
  $items['import/%feeds_importer/history'] = array(
    'title' => 'History',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'feeds_dashboard_show_history',
    'page arguments' => array(1),
    'access callback' => 'feeds_access',
    'access arguments' => array('import', 1),
    'file' => 'feeds_dashboard.pages.inc',
    'weight' => -9,
  );
  $items['import/%feeds_importer/history/operation/%'] = array(
    'title' => 'Operation',
    'type' => MENU_CALLBACK,
    'page callback' => 'feeds_dashboard_show_operation',
    'page arguments' => array(1,4),
    'access callback' => 'feeds_access',
    'access arguments' => array('import', 1),
    'file' => 'feeds_dashboard.pages.inc',
  );
  $items['import/%feeds_importer/history/operation/%/%'] = array(
    'title' => 'Operation content',
    'type' => MENU_CALLBACK,
    'page callback' => 'feeds_dashboard_show_operation_content',
    'page arguments' => array(1,4,5),
    'access callback' => 'feeds_access',
    'access arguments' => array('import', 1),
    'file' => 'feeds_dashboard.pages.inc',
  );

  return $items;
}

/**
 * Invoked before a feed source import starts.
 *
 * @param FeedsSource $source
 *  FeedsSource object that describes the source that is going to be imported.
 */
function feeds_dashboard_feeds_before_import(FeedsSource $source) {
  // Create log in database and get dashboard id.
  $source->did = db_insert('feeds_dashboard')
    ->fields(array(
      'operation_description' => 'Started importing.',
      'id' => $source->id,
      'file' => '',
      'date' => date('Y-m-d H:i:s'),
    ))
    ->execute();
}

/**
 * Invoked after a feed source has been imported.
 *
 * @param FeedsSource $source
 *  FeedsSource object that describes the source that has been imported.
 */
function feeds_dashboard_feeds_after_import(FeedsSource $source) {
  // Copy the source file to specific folder for history purpose.
  $file = file_load($source->config['FeedsFileFetcher']['fid']);
  $destination = drupal_realpath('public://') . '/feeds_dashboard/';

  if (file_prepare_directory($destination, FILE_CREATE_DIRECTORY)) {
    $destination = file_stream_wrapper_uri_normalize('public://feeds_dashboard/' . drupal_basename($file));
    $copied_file = file_copy($file, $destination, FILE_EXISTS_RENAME);

    // Log the import.
    if(!empty($copied_file)) {
      $results = $source->state['process'];
      $operation_description = t('@skipped skipped, @created created, @updated updated, @deleted deleted.', array('@skipped' => $results->skipped, '@created' => $results->created, '@updated' => $results->updated, '@deleted' => $results->deleted));

      db_update('feeds_dashboard')
        ->fields(array(
          'operation_description' => $operation_description,
          'file' => $copied_file->uri,
          'date' => date('Y-m-d H:i:s'),
        ))
        ->condition('did', $source->did, '=')
        ->execute();
    } else {
      drupal_set_message(t("Error while copying import file, please check file writing permission to public:// folder"), 'error', FALSE);
    }
  } else {
    drupal_set_message(t("Error while creating import folder, please check file writing permission to public:// folder"), 'error', FALSE);
  }
}


/**
 * Invoked after a feed source has been cleared of its items.
 *
 * @param FeedsSource $source
 *  FeedsSource object that describes the source that has been cleared.
 */
function feeds_dashboard_feeds_after_clear(FeedsSource $source) {
  watchdog('feeds_dashboard', "<pre>" . print_r($source, true) . "</pre>");
  // Log feed deletion.
  $results = $source->state['process_clear'];
  $operation_description = t('<span class="fd-content-clear">Feed content clear</span>: @skipped skipped, @created created, @updated updated, @deleted deleted.', array('@skipped' => $results->skipped, '@created' => $results->created, '@updated' => $results->updated, '@deleted' => $results->deleted));

  db_insert('feeds_dashboard')
    ->fields(array(
      'id' => $source->id,
      'operation_description' => $operation_description,
      'date' => date('Y-m-d H:i:s'),
    ))
    ->execute();
}

/**
 * Invoked after a feed item has been saved.
 *
 * @param FeedsSource $source
 *  FeedsSource object that describes the source that is being imported.
 * @param $entity
 *   The entity object that has just been saved.
 * @param array $item
 *   The parser result for this entity.
 * @param int|null $entity_id
 *  The id of the current item which is going to be updated. If this is a new
 *  item, then NULL is passed.
 */
function feeds_dashboard_feeds_after_save(FeedsSource $source, $entity, $item, $entity_id) {
  // Log content created.
  db_insert('feeds_dashboard_operations')
    ->fields(array(
      'did' => $source->did,
      'entity' => serialize($entity),
      'content' => serialize($item),
      'entity_id' => $entity_id,
    ))
    ->execute();
}

/**
 * Implements hook_theme().
 */
function feeds_dashboard_theme() {
  $theme_subfolder = drupal_get_path('module', 'feeds_dashboard') . '/theme';
  $items['feeds_dashboard_history_page'] = array(
    'variables' => array('operations' => array()),
    'path' => $theme_subfolder,
    'template' => 'feeds-dashboard--history',
  );
  $items['feeds_dashboard_details'] = array(
    'variables' => array('data' => array()),
    'path' => $theme_subfolder,
    'template' => 'feeds-dashboard--table',
  );

  return $items;
}


/**
 * Returns an array of operations given a feed id.
 *
 * @param string $id
 *   Id of the feed configuration.
 */
function feeds_dashboard_get_operations_for_feed($id) {
  $operations = db_select('feeds_dashboard', 'fd')
    ->fields('fd')
    ->condition('id', $id, '=')
    ->orderBy('date', 'DESC')
    ->execute()
    ->fetchAllAssoc('did');

  return $operations;
}

/**
 * Returns an operation given an operation id.
 *
 * @param int $did
 *   operation id.
 */
function feeds_dashboard_get_operation($did) {
  $operation = db_select('feeds_dashboard', 'fd')
    ->fields('fd')
    ->condition('did', $did, '=')
    ->execute()
    ->fetchAllAssoc('did');

  return $operation;
}

/**
 * Returns import data given an import id.
 *
 * @param int $imid
 *   import id.
 */
function feeds_dashboard_get_imported_data($imid) {
  $data = db_select('feeds_dashboard_operations', 'fdo')
    ->fields('fdo')
    ->condition('imid', $imid, '=')
    ->execute()
    ->fetchAssoc();

  return $data;
}

/**
 * Returns an array of imported content
 * given an operation id.
 *
 * @param string $did
 *   Id of the operation.
 */
function feeds_dashboard_get_data_for_operation($did) {
  $data = db_select('feeds_dashboard_operations', 'fdo')
    ->fields('fdo')
    ->condition('did', $did, '=')
    ->orderBy('imid', 'ASC')
    ->execute()
    ->fetchAllAssoc('imid');

  return $data;
}